### ISSUE TITLE
Parsing fails to parse Lists in ResTarget nodes

### ISSUE THREAD

**Issue by NAlexPear** [paupino/pg_parse#1]
### Summary:

For example queries with lists of values like `INSERT INTO contacts.person(name, ssn) VALUES ($1, $2)`, `parse()` fails with an error of: 

```
unknown variant `List`, expected one of <every variant of Node>
```

### How to fix it:

As far as I can tell, this is a consequence of treating every `List` as an `Option<Vec<Node>>`, which works _most_ of the time, but not in this specific case of parsing lists of params in `ResTarget` nodes.

I've included a [hacky fix on my fork of `pg_query.rs`](https://github.com/NAlexPear/pg_query.rs/commit/bd3f3449f25b35eb939e67cd84e1f0560ffabd6f#diff-d0d98998092552a1d3259338c2c71e118a5b8343dd4703c0c7f552ada7f9cb42) that special-cases `List` and creates a `List` `struct` with an `items` field, similar to how `List` is handled in the [`go` library](https://pkg.go.dev/github.com/lfittl/pg_query_go/nodes#List), and creates a separate [`List` variant of `Node`](https://github.com/NAlexPear/pg_query.rs/commit/bd3f3449f25b35eb939e67cd84e1f0560ffabd6f#diff-d0d98998092552a1d3259338c2c71e118a5b8343dd4703c0c7f552ada7f9cb42R316). This [solves the issue for the test case above](https://github.com/NAlexPear/pg_query.rs/commit/bd3f3449f25b35eb939e67cd84e1f0560ffabd6f). 

If this :point_up: approach is acceptable, let me know and I'll put together a PR. A downside to this approach is the split treatment of `List` across the codebase: in _most_ cases, it becomes an `Option<Vec<Node>>` (see the other existing parsing tests), but not in the case of e.g. `VALUES` lists. This doesn't bother me too much for my particular use-case, but would be surprising from someone used to the `go` implementation's approach of using `List` everywhere instead of `Node[]`. A different implementation might be to use a separate `List` type like the one I've hacked into the build script, but implement `IntoIterator` and `ExactSizedIterator` and friends to make working with `List` exactly like working with `Vec<Node>` for backwards-compatibility.

Thanks for creating this crate, and let me know how you'd like to proceed!

**Comment by paupino** [comment]
Ah, interesting - thank you for raising the issue as well as the great write up!

I think you're right by aligning with how the go library handles the `List` variant. I think for the meantime, it's a good step forward - the approach you've taken can also be iteratively improved (as you mention) by implementing `IntoIterator` etc. I'd be happy to take this approach for now.

Thanks for your help!

**Comment by NAlexPear** [comment]
Perhaps the simplest solution (if you're OK with API incompatibility) would be to move entirely to the `pg_query_go` approach and use `libpg_query`'s own protobuf definitions to define Rust types. That way we can be confident that we'll never be too far out of lockstep with the canonical `pg_query` versions.

[Here's an implementation I put together](https://github.com/NAlexPear/pg_query_rust) that uses [`prost`](https://github.com/tokio-rs/prost) to compile those protos into Rust types, saving us the trouble of extracting Rust types manually from those JSON files at the cost of a slightly different API. As far as maintenance goes, [this build script](https://github.com/NAlexPear/pg_query_rust/blob/main/build.rs#L25) and [this function](https://github.com/NAlexPear/pg_query_rust/blob/main/src/lib.rs#L49) should be sufficient to avoid issues like this one in the future while scrapping a few hundred lines of JSON-parsing.

Is this an acceptable approach? If it is, then I'd be happy to a) spin out those `libpg_query` bindings out into a separate crate (`libpgquery-sys`, perhaps) and b) submit a PR patching those proto-based definitions into [`query.rs`](https://github.com/paupino/pg_query.rs/blob/master/src/query.rs).

**Comment by seanlinsley** [comment]
Over at pganalyze we're moving some code to Rust, so needed more of the features from the Ruby version of pg_query. Here's the implementation so far: https://github.com/seanlinsley/pg_query.rs. It uses the protobuf definition and implements methods like `deparse` and `truncate`. Unfortunately `truncate` has to rely on a lot of unsafe code...

@NAlexPear I tried to use your code originally, but I ran into issues compiling on Apple silicon and couldn't work around it

Let me know if y'all have any feedback on the code so far. We'd of course be happy to contribute this upstream and/or take over the maintenance burden of the project.

**Comment by NAlexPear** [comment]
@seanlinsley thanks for jumping in on this thread! It's been quiet for a while.

> I tried to use your code originally, but I ran into issues compiling on Apple silicon and couldn't work around it

Since making this issue, I've spun up [`libpgquery-sys`](https://github.com/NAlexPear/libpgquery-sys) as a separate crate to handle bindings to the underlying `libpgquery` library and to clean up the build system, relying on `prost` + protobufs instead (and used in [`postguard`](https://github.com/boilerplatter/postgrpc/tree/master/postguard)).

`libpgquery-sys` (incorrectly, I think) includes a [`parseToProtobuf`](https://github.com/NAlexPear/libpgquery-sys/blob/main/src/lib.rs#L49) function that does everything that _I_ need, but obviously isn't as high-powered as the Ruby library. So far, I really like the protobuf + `prost` approach here, rather than the bespoke build script approach, but both are probably viable.

As for moving forward and maintenance burden: perhaps using `libpgquery-sys` as a proper set of `unsafe` bindings that expose a lower-level API upon which a safe `deparse` and `truncate` could be built might be the right approach here. That's the Rust-y way of doing it, at least: separating the lower-level `*-sys` bindings into a crate separate from the higher-level/safe APIs. Just let me know where you'd best like me to contribute (whether those higher-level bindings would be owned by @paupino or `pganalyze`).

**Comment by paupino** [comment]
@NAlexPear I quite like that approach and gives people flexibility into integrating with the appropriate level for their requirements.

More than happy to accept submissions and review whatever needs reviewing. Admittedly I haven't been focusing too much in the `pgquery` realm lately so am less familiar with current problems/issues however I'd definitely be open to adding additional maintainers of the system to help run the show. It'd also perhaps be useful to have someone share the crates.io ownership.

**Comment by seanlinsley** [comment]
@NAlexPear sorry, to clarify:
- https://github.com/seanlinsley/pg_query.rs already uses protobuf and prost. I tried to reuse the work you did, but fell back to this repo's compilation step because your version wouldn't compile on Apple silicon for some reason. I'm not opposed to using libpgquery-sys, but it not compiling is a blocker for now.
- the unsafe code I referenced isn't low-level: it's the entirety of the [truncate function](https://github.com/seanlinsley/pg_query.rs/blob/618de31b5b6fb1252b8089ad8bbe0ffb02f8ecd4/src/truncate.rs#L36) because this sort of recursive mutation isn't something Rust can safely support

At this point the code is nearly complete -- I've already ported over the features and tests we need from the Ruby library. The only remaining tasks are updating the documentation, and code review by y'all and us internally.

**Comment by NAlexPear** [comment]
@seanlinsley Got it! Sorry, wasn't clear if you were originally referring to `libpgquery-sys` or to my fork of _this_ project. Looks like you were referring to `libpgquery-sys`, which makes sense. Apologies for the confusion. I'm already updating `libpgquery-sys` with a more robust compilation pipeline that should work on M1 (as well as a more restricted scope, as befits a `*-sys` crate), if that's something you or @paupino would be interested in.

It's unlikely that I'll use any of the APIs of this library or its fork(s) in the near future (I basically only need to pattern match on the protobuf results from `parse`, which is easy enough to implement in my own application), so I'll be maintaining `libpgquery-sys` for my own uses anyway.
